config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root "inbox#show"
    get "inbox", to: "inbox#show"

    resources :playables, only: :create
  end

  resources :lists, only: %i[show update] do
    resources :playables, only: :show

    member do
      authenticate :user do
        patch "active_playable"
        patch "toggle_repeat"
        patch "toggle_shuffle"
      end
    end
  end
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id           :uuid             not null, primary key
#  inbox        :boolean          default(FALSE)
#  max_duration :float            default(30.0)
#  name         :string
#  public       :boolean          default(FALSE)
#  slug         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  owner_id     :uuid             not null
#
# Indexes
#
#  index_lists_on_owner_id  (owner_id)
#  index_lists_on_slug      (slug) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (owner_id => users.id)
#
class List < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  broadcasts

  belongs_to :owner, class_name: "User"

  has_many :list_memberships
  has_many :users, through: :list_memberships

  has_many :playable_list_items, -> { order(position: :asc) }
  has_many :playables, through: :playable_list_items

  validates :inbox, uniqueness: {scope: :owner, message: "A user can have only one inbox"}

  kredis_hash :active_playables
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show update active_playable toggle_repeat toggle_shuffle]
  before_action :set_active_playable, only: %i[show toggle_repeat toggle_shuffle]

  def show
    @new_playables = current_user.inbox.playables.where.not(id: @list.playables.pluck(:id)).unscope(:order).order(created_at: :desc)
    authenticate_user! unless @list.public
  end

  def update
    @list.playables << Playable.find(list_params[:playable_id])

    if @list.update(list_params.except(:playable_id))
      render turbo_stream: turbo_stream.replace(@list, partial: "lists/list", locals: {list: @list, user: current_user})
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def active_playable
    @list.active_playables[current_user.id] = Playable.find(list_params[:active_playable_id]).to_gid.to_s

    # TODO make this a .turbo_stream.erb partial
    render turbo_stream: turbo_stream.replace(@list, partial: "lists/list", locals: {list: @list, user: current_user})
  end

  # TODO everything that doesn't feel RESTy should go into SR?
  def toggle_repeat
    session[@list.to_gid.to_s][:repeat] = !session[@list.to_gid.to_s].fetch("repeat", false)

    render turbo_stream: turbo_stream.replace(@list, partial: "lists/list", locals: {list: @list, user: current_user})
  end

  def toggle_shuffle
    session[@list.to_gid.to_s][:shuffle] = !session[@list.to_gid.to_s].fetch("shuffle", false)

    render turbo_stream: turbo_stream.replace(@list, partial: "lists/list", locals: {list: @list, user: current_user})
  end

  private

  def list_params
    params.require(:list).permit(:active_playable_id, :playable_id)
  end

  def set_list
    @list = List.friendly.find(params[:id])
    session[@list.to_gid.to_s] ||= {}
  end

  def set_active_playable
    @list.active_playables[current_user.id] ||= @list.playables.first.to_gid.to_s
  end
end

app/views/lists/_list.html.erb
<% active = GlobalID::Locator.locate(list.active_playables[user.id]) %>

<%= turbo_frame_tag list do %>
  <%= content_tag :div, class: "border border-dashed border-2 border-gray-400 p-4" do %>
    <tapestry-element maxduration="<%= list.max_duration %>" items="<%= list.playables.map { |entry| {id: entry.id, duration: entry.listable.duration.in_minutes, color: ["#F87171", "#34D399", "#F472B6", "#4ADE80", "#38BDF8", "#818CF8"].sample} }.to_json %>" listid="<%= list.id %>" activeid="<%= active&.id %>"></tapestry-element>
  <% end %>

  <%= form_with(model: list, url: active_playable_list_path(list), id: dom_id(list, :active_playable)) do |f| %>
    <%= f.hidden_field :active_playable_id, {value: active.id} %>
  <% end %>

  <%= turbo_frame_tag "active_playable", src: list_playable_url(list, active) if active.present? %>
<% end %>

app/views/lists/show.html.erb
<%= content_for :modal do %>
  <%= render "lists/modals/new", list: @list, playables: @new_playables %>
<% end %>

<div class="space-y-6">
  <div class="px-4 py-5 sm:px-6">
    <div class="flex space-x-3">
      <div class="min-w-0 flex-1">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          <%= @list.name %>
        </h3>
        <!-- <p class="text-sm text-gray-500">
             <a href="#" class="hover:underline">December 9 at 11:43 AM</a>
             </p> -->
      </div>
      <div class="flex-shrink-0 self-center flex">
        <div class="relative z-30 inline-block text-left"
             data-controller="dropdown"
             data-dropdown-invisible-class="opacity-0 scale-95"
             data-dropdown-visible-class="opacity-100 scale-100"
             data-dropdown-entering-class="ease-out duration-100"
             data-dropdown-enter-timeout="100"
             data-dropdown-leaving-class="ease-in duration-75"
             data-dropdown-leave-timeout="75"
        >
          <div>
            <button data-action="click->dropdown#toggle click@window->dropdown#hide" data-dropdown-target="button" type="button" class="-m-2 p-2 rounded-full flex items-center text-gray-400 hover:text-gray-600" id="menu-0-button" aria-expanded="false" aria-haspopup="true">
              <span class="sr-only">Open options</span>
              <i class="fa-solid fa-ellipsis-vertical"></i>
            </button>
          </div>
          <div data-dropdown-target="menu" class="origin-top-right absolute right-0 mt-2 w-56 shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none transition transform hidden" role="menu" aria-orientation="vertical" aria-labelledby="menu-0-button" tabindex="-1">
            <div class="py-1" role="none">
              <%= link_to "#",
                   class: "text-gray-700 flex px-4 py-2 text-sm hover:text-gray-900 hover:bg-gray-100",
                   data: {action: "click->dropdown#_hide click->modal#open"},
                   role: "menuitem",
                   tabindex: "-1" do %>
                <i class="fas fa-plus mr-3 h-5 w-5 text-gray-400"></i> 
                <span>Add a track to this tapestry</span>
              <% end %>
              <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
              <!-- <a href="#" class="text-gray-700 flex px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-0-item-0"> -->
                <!-- Heroicon name: solid/star -->
              <!-- <svg class="mr-3 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"> -->
              <!-- <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" /> -->
              <!-- </svg> -->
              <!-- <span>Add to favorites</span> -->
              <!-- </a> -->
              <!-- <a href="#" class="text-gray-700 flex px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-0-item-1"> -->
                <!-- Heroicon name: solid/code -->
              <!-- <svg class="mr-3 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                   <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
                   </svg>
                   <span>Embed</span>
                   </a> -->
              <!-- <a href="#" class="text-gray-700 flex px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-0-item-2"> -->
                <!-- Heroicon name: solid/flag -->
              <!-- <svg class="mr-3 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                   <path fill-rule="evenodd" d="M3 6a3 3 0 013-3h10a1 1 0 01.8 1.6L14.25 8l2.55 3.4A1 1 0 0116 13H6a1 1 0 00-1 1v3a1 1 0 11-2 0V6z" clip-rule="evenodd" />
                   </svg>
                   <span>Report content</span>
                   </a> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= turbo_stream_from @list %>
  
  <%= render @list, user: current_user %>
</div>