config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root "inbox#show"
    get "inbox", to: "inbox#show"

    resources :playables, only: :create
  end

  resources :lists, only: %i[show update] do
    resources :playables, only: :show

    member do
      authenticate :user do
        patch "active_playable"
        patch "toggle_repeat"
        patch "toggle_shuffle"
      end
    end
  end
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id           :uuid             not null, primary key
#  inbox        :boolean          default(FALSE)
#  max_duration :float            default(30.0)
#  name         :string
#  public       :boolean          default(FALSE)
#  slug         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  owner_id     :uuid             not null
#
# Indexes
#
#  index_lists_on_owner_id  (owner_id)
#  index_lists_on_slug      (slug) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (owner_id => users.id)
#
class List < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  broadcasts

  belongs_to :owner, class_name: "User"

  has_many :list_memberships
  has_many :users, through: :list_memberships

  has_many :playable_list_items, -> { order(position: :asc) }
  has_many :playables, through: :playable_list_items

  validates :inbox, uniqueness: {scope: :owner, message: "A user can have only one inbox"}

  kredis_hash :active_playables
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show update active_playable toggle_repeat toggle_shuffle]
  before_action :set_active_playable, only: %i[show toggle_repeat toggle_shuffle]

  def show
    @new_playables = current_user.inbox.playables.where.not(id: @list.playables.pluck(:id)).unscope(:order).order(created_at: :desc)
    authenticate_user! unless @list.public
  end

  def update
    @list.playables << Playable.find(list_params[:playable_id])

    if @list.update(list_params.except(:playable_id))
      render turbo_stream: turbo_stream.replace(@list, partial: "lists/list", locals: {list: @list, user: current_user})
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def active_playable
    @list.active_playables[current_user.id] = Playable.find(list_params[:active_playable_id]).to_gid.to_s

    # TODO make this a .turbo_stream.erb partial
    render turbo_stream: turbo_stream.replace(@list, partial: "lists/list", locals: {list: @list, user: current_user})
  end

  # TODO everything that doesn't feel RESTy should go into SR?
  def toggle_repeat
    session[@list.to_gid.to_s][:repeat] = !session[@list.to_gid.to_s].fetch("repeat", false)

    render turbo_stream: turbo_stream.replace(@list, partial: "lists/list", locals: {list: @list, user: current_user})
  end

  def toggle_shuffle
    session[@list.to_gid.to_s][:shuffle] = !session[@list.to_gid.to_s].fetch("shuffle", false)

    render turbo_stream: turbo_stream.replace(@list, partial: "lists/list", locals: {list: @list, user: current_user})
  end

  private

  def list_params
    params.require(:list).permit(:active_playable_id, :playable_id)
  end

  def set_list
    @list = List.friendly.find(params[:id])
    session[@list.to_gid.to_s] ||= {}
  end

  def set_active_playable
    @list.active_playables[current_user.id] ||= @list.playables.first.to_gid.to_s
  end
end

app/views/lists/modals/_new.html.erb
<div class="fixed z-10 inset-0 overflow-y-auto hidden" aria-labelledby="modal-title" role="dialog" aria-modal="true" data-modal-target="container">
  <div class="flex items-start justify-center min-h-screen px-4 pt-20 pb-4 text-center sm:block sm:p-0">
    <!--
      Background overlay, show/hide based on modal state.
    -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity opacity-0" data-modal-target="overlay" aria-hidden="true"></div>

    <!-- This element is to trick the browser into centering the modal contents. -->
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

    <!--
      Modal panel, show/hide based on modal state.
    -->
    <div data-modal-target="modal" class="inline-block align-bottom bg-white px-4 pt-5 pb-4 text-left overflow-hidden shadow-sm transform transition-all sm:my-8 sm:align-middle sm:max-w-lg md:max-w-xl lg:max-w-2xl w-full sm:p-6 opacity-0 -translate-y-4 sm:translate-y-0 sm:scale-95">
      <div class="block absolute top-0 right-0 pt-4 pr-4">
        <button data-action="click->modal#close" type="button" class="bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500">
          <span class="sr-only">Close</span>
          <!-- Heroicon name: outline/x -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="">
        <div class="text-center">
          <i class="fas fa-music mx-auto h-12 w-12 text-gray-400"></i>
          <h2 class="mt-2 text-lg font-medium text-gray-900">Add a track to <span class="text-primary-800"><%= list.name %></span></h2>
          <!-- if list is empty -->
          <!-- <p class="mt-1 text-sm text-gray-500">
               You haven’t added any team members to your project yet.
               </p> -->
          <div class="mt-10">
            <h3 class="text-xs font-semibold text-gray-500 uppercase tracking-wide">Recommended tracks</h3>
            <ul role="list" class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
              <%= render playables, link_path: list_path(@list) %>
            </ul>
          </div>
        </div>
      </div>
      <!-- <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
           <button type="button" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm">
           Deactivate
           </button>
           <button data-action="click->modal#close" type="button" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 sm:mt-0 sm:w-auto sm:text-sm">
           Cancel
           </button>
           </div> -->
    </div>
  </div>
</div>